#!/usr/bin/env node
/**
 * One-time setup for zero-touch pairing: registers the native messaging host
 * (mcp-server/dist/native-host.js) with the Chromium browsers on this machine,
 * so the extension fetches the enrollment secret itself instead of the user
 * pasting it into the popup.
 *
 *   node scripts/pairing.mjs install [--extension-id <id>]...   npm run setup:pairing
 *   node scripts/pairing.mjs status                             npm run pairing:status
 *   node scripts/pairing.mjs uninstall                          npm run pairing:uninstall
 *
 * Chrome lets only the extension IDs in the manifest's allowed_origins start
 * the host. The ID of an unpacked extension is derived from its folder path,
 * so it is computed here from <repo>/extension; pass --extension-id when the
 * extension is loaded from somewhere else.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

/** Must match NATIVE_HOST_NAME in mcp-server/src/native-host.ts (tests check it). */
export const HOST_NAME = 'com.browser_controller.pairing';

const REPO_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const EXTENSION_ID = /^[a-p]{32}$/;

/** [display name, user-data folder relative to the platform's base folder] */
const BROWSERS = {
  darwin: [
    ['Google Chrome', 'Google/Chrome'],
    ['Google Chrome Beta', 'Google/Chrome Beta'],
    ['Google Chrome Canary', 'Google/Chrome Canary'],
    ['Chromium', 'Chromium'],
    ['Microsoft Edge', 'Microsoft Edge'],
    ['Brave', 'BraveSoftware/Brave-Browser'],
  ],
  linux: [
    ['Google Chrome', 'google-chrome'],
    ['Google Chrome Beta', 'google-chrome-beta'],
    ['Google Chrome Dev', 'google-chrome-unstable'],
    ['Chromium', 'chromium'],
    ['Microsoft Edge', 'microsoft-edge'],
    ['Brave', 'BraveSoftware/Brave-Browser'],
  ],
  /** Registry path under HKCU\Software */
  win32: [
    ['Google Chrome', 'Google\\Chrome'],
    ['Chromium', 'Chromium'],
    ['Microsoft Edge', 'Microsoft\\Edge'],
    ['Brave', 'BraveSoftware\\Brave-Browser'],
  ],
};

/**
 * Chrome's ID for an extension loaded unpacked from `dir` (pass the real
 * path): the first 128 bits of SHA-256 over the path, hex digits mapped to
 * a–p. Windows hashes the UTF-16 path with an upper-case drive letter.
 */
export function unpackedExtensionId(dir, platform = process.platform) {
  let bytes;
  if (platform === 'win32') {
    const p = /^[a-z]:/.test(dir) ? dir[0].toUpperCase() + dir.slice(1) : dir;
    bytes = Buffer.from(p, 'utf16le');
  } else {
    bytes = Buffer.from(dir, 'utf8');
  }
  const hex = crypto.createHash('sha256').update(bytes).digest('hex').slice(0, 32);
  return [...hex].map((c) => String.fromCharCode(97 + parseInt(c, 16))).join('');
}

/** Where each installed browser looks for user-level native messaging hosts. */
export function browserTargets({ platform, home, xdgConfigHome }) {
  if (platform === 'win32') {
    return BROWSERS.win32.map(([name, rel]) => ({
      name,
      regKey: `HKCU\\Software\\${rel}\\NativeMessagingHosts\\${HOST_NAME}`,
    }));
  }
  const base = platform === 'darwin'
    ? path.join(home, 'Library', 'Application Support')
    : (xdgConfigHome || path.join(home, '.config'));
  return (BROWSERS[platform] || BROWSERS.linux).map(([name, rel]) => {
    const userDataDir = path.join(base, rel);
    return { name, userDataDir, manifestPath: path.join(userDataDir, 'NativeMessagingHosts', `${HOST_NAME}.json`) };
  });
}

const shellQuote = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`;

/**
 * The executable Chrome starts. It pins the absolute node path: a browser
 * started from the Dock/Start menu does not see the shell's PATH (nvm,
 * Homebrew), so `#!/usr/bin/env node` would fail there.
 */
export function wrapperScript({ platform, nodePath, hostJs, stateDir }) {
  if (platform === 'win32') {
    return [
      '@echo off',
      'rem Generated by `npm run setup:pairing` (Browser Controller pairing host).',
      ...(stateDir ? [`set "BC_STATE_DIR=${stateDir}"`] : []),
      `"${nodePath}" "${hostJs}" %*`,
      '',
    ].join('\r\n');
  }
  return [
    '#!/bin/sh',
    '# Generated by `npm run setup:pairing` (Browser Controller pairing host).',
    ...(stateDir ? [`export BC_STATE_DIR=${shellQuote(stateDir)}`] : []),
    `exec ${shellQuote(nodePath)} ${shellQuote(hostJs)} "$@"`,
    '',
  ].join('\n');
}

export function hostManifest({ wrapperPath, extensionIds }) {
  return {
    name: HOST_NAME,
    description: 'Browser Controller pairing: hands the local enrollment secret to the Browser Controller extension',
    path: wrapperPath,
    type: 'stdio',
    allowed_origins: extensionIds.map((id) => `chrome-extension://${id}/`),
  };
}

function paths({ repoRoot, platform }) {
  const wrapperDir = path.join(repoRoot, '.native-host');
  return {
    hostJs: path.join(repoRoot, 'mcp-server', 'dist', 'native-host.js'),
    wrapperDir,
    wrapperPath: path.join(wrapperDir, platform === 'win32' ? `${HOST_NAME}.bat` : HOST_NAME),
    windowsManifest: path.join(wrapperDir, `${HOST_NAME}.json`),
  };
}

const runReg = (args) => execFileSync('reg', args, { stdio: 'ignore' });

export function install({
  platform = process.platform,
  home = os.homedir(),
  xdgConfigHome = process.env.XDG_CONFIG_HOME,
  repoRoot = REPO_ROOT,
  nodePath = process.execPath,
  stateDir = process.env.BC_STATE_DIR,
  extensionIds,
  reg = runReg,
} = {}) {
  const p = paths({ repoRoot, platform });
  if (!fs.existsSync(p.hostJs)) throw new Error(`${p.hostJs} not found — run \`npm run build\` first.`);
  if (!extensionIds?.length) throw new Error('No extension ID to allow.');

  fs.mkdirSync(p.wrapperDir, { recursive: true });
  fs.writeFileSync(p.wrapperPath, wrapperScript({ platform, nodePath, hostJs: p.hostJs, stateDir }), { mode: 0o755 });
  fs.chmodSync(p.wrapperPath, 0o755);
  const manifest = JSON.stringify(hostManifest({ wrapperPath: p.wrapperPath, extensionIds }), null, 2) + '\n';

  const installed = [];
  const skipped = [];
  if (platform === 'win32') {
    fs.writeFileSync(p.windowsManifest, manifest);
    for (const t of browserTargets({ platform, home, xdgConfigHome })) {
      try {
        reg(['add', t.regKey, '/ve', '/t', 'REG_SZ', '/d', p.windowsManifest, '/f']);
        installed.push(t.name);
      } catch {
        skipped.push(t.name);
      }
    }
  } else {
    for (const t of browserTargets({ platform, home, xdgConfigHome })) {
      if (!fs.existsSync(t.userDataDir)) { skipped.push(t.name); continue; }
      fs.mkdirSync(path.dirname(t.manifestPath), { recursive: true });
      fs.writeFileSync(t.manifestPath, manifest);
      installed.push(t.name);
    }
  }
  return { extensionIds, wrapperPath: p.wrapperPath, installed, skipped };
}

export function uninstall({
  platform = process.platform,
  home = os.homedir(),
  xdgConfigHome = process.env.XDG_CONFIG_HOME,
  repoRoot = REPO_ROOT,
  reg = runReg,
} = {}) {
  const removed = [];
  for (const t of browserTargets({ platform, home, xdgConfigHome })) {
    if (platform === 'win32') {
      try { reg(['delete', t.regKey, '/f']); removed.push(t.name); } catch { /* not registered */ }
    } else if (fs.existsSync(t.manifestPath)) {
      fs.rmSync(t.manifestPath);
      removed.push(t.name);
    }
  }
  fs.rmSync(paths({ repoRoot, platform }).wrapperDir, { recursive: true, force: true });
  return { removed };
}

/** What is registered where. Never reads out the secret itself. */
export function status({
  platform = process.platform,
  home = os.homedir(),
  xdgConfigHome = process.env.XDG_CONFIG_HOME,
  repoRoot = REPO_ROOT,
  stateDir = process.env.BC_STATE_DIR || path.join(os.homedir(), '.browser-controller'),
} = {}) {
  const p = paths({ repoRoot, platform });
  const browsers = [];
  if (platform !== 'win32') {
    for (const t of browserTargets({ platform, home, xdgConfigHome })) {
      if (!fs.existsSync(t.manifestPath)) continue;
      let allowed = [];
      try { allowed = JSON.parse(fs.readFileSync(t.manifestPath, 'utf8')).allowed_origins || []; } catch { /* unreadable */ }
      browsers.push({ name: t.name, allowedOrigins: allowed });
    }
  }
  let enrollment = false;
  try { enrollment = !!JSON.parse(fs.readFileSync(path.join(stateDir, 'enrollment.json'), 'utf8')).secret; } catch { /* none yet */ }
  return {
    hostBuilt: fs.existsSync(p.hostJs),
    wrapperPath: fs.existsSync(p.wrapperPath) ? p.wrapperPath : null,
    browsers,
    enrollment,
  };
}

function parseArgs(argv) {
  const [command = 'install', ...rest] = argv;
  const extensionIds = [];
  let extensionDir = path.join(REPO_ROOT, 'extension');
  for (let i = 0; i < rest.length; i++) {
    if (rest[i] === '--extension-id') extensionIds.push(rest[++i]);
    else if (rest[i] === '--extension-dir') extensionDir = rest[++i];
    else throw new Error(`Unknown option ${rest[i]}`);
  }
  for (const id of extensionIds) {
    if (!EXTENSION_ID.test(id || '')) throw new Error(`Invalid extension ID "${id}" (32 letters a–p, as shown in chrome://extensions).`);
  }
  return { command, extensionIds, extensionDir };
}

function main() {
  const { command, extensionIds, extensionDir } = parseArgs(process.argv.slice(2));
  if (command === 'install') {
    const dir = fs.realpathSync(extensionDir);
    const ids = extensionIds.length ? extensionIds : [unpackedExtensionId(dir)];
    const r = install({ extensionIds: ids });
    console.log('Browser Controller pairing host');
    console.log(`  Extension ID: ${ids.join(', ')}${extensionIds.length ? '' : ` (unpacked from ${dir})`}`);
    console.log('  It must match the ID shown for Browser Controller in chrome://extensions.');
    if (r.installed.length === 0) {
      console.error('  No Chromium browser found to register with. Open the browser once, then run this again.');
      process.exit(1);
    }
    console.log(`  Registered with: ${r.installed.join(', ')}`);
    console.log('\nNext: click Reload on Browser Controller in chrome://extensions — it pairs itself, nothing to paste.');
    return;
  }
  if (command === 'uninstall') {
    const r = uninstall();
    console.log(r.removed.length ? `Removed from: ${r.removed.join(', ')}` : 'Nothing was registered.');
    return;
  }
  if (command === 'status') {
    const s = status();
    const id = unpackedExtensionId(fs.realpathSync(extensionDir));
    console.log(`Expected extension ID: ${id} (unpacked from ${fs.realpathSync(extensionDir)})`);
    console.log(`Host built: ${s.hostBuilt ? 'yes' : 'no — run npm run build'}`);
    console.log(`Launcher: ${s.wrapperPath || 'missing — run npm run setup:pairing'}`);
    console.log(`Enrollment secret on disk: ${s.enrollment ? 'yes' : 'no — start your MCP client once'}`);
    if (process.platform === 'win32') {
      console.log('Browsers: see HKCU\\Software\\<browser>\\NativeMessagingHosts\\' + HOST_NAME);
    } else if (s.browsers.length === 0) {
      console.log('Browsers: none registered — run npm run setup:pairing');
    } else {
      for (const b of s.browsers) {
        const ok = b.allowedOrigins.includes(`chrome-extension://${id}/`);
        console.log(`Browser: ${b.name} — ${ok ? 'allows this extension' : `allows ${b.allowedOrigins.join(', ') || 'nothing'} (not ${id})`}`);
      }
    }
    return;
  }
  throw new Error(`Unknown command "${command}" (install | status | uninstall)`);
}

if (process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url))) {
  try {
    main();
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
}
